### PR TITLE
Add boolean type

### PR DESCRIPTION
**Pull request by Chemaclass**
## 📚 Description

Add boolean ColumnDefinition to the Schema.

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Hello Jose,

nice to see you in my latest project 👋.

I did not see your pull request until after I finished working on a change that now causes a conflict with your changes.

Can you please resolve the conflict? Thanks!

**Comment by Chemaclass** [comment]
I will fix those broken tests 🏗️

**Comment by sebastianbergmann** [comment]
Can you please rebase against `main` (or squash your changes into a single commit)? I would like to avoid merge commits. Thanks!

**Comment by Chemaclass** [comment]
Of course, @sebastianbergmann! There you go. Just one beautiful commit, freshly _rebased_ and _squashed_ for you :)

**Comment by sebastianbergmann** [comment]
Thank you!

**Pull request merged**
