### PR TITLE
Use an abstract method instead of a bunch of `if`s

### PR DESCRIPTION
**Pull request by MidnightDesign**

### CODE REVIEW

**Comment by MidnightDesign** [comment]
This enables users of the library to implement custom types like Enums:

```php
enum Pet: string {
    case Dog = 'dog';
    case Dragon = 'dragon';
}

final class PetType extends Type
{
    public function cast(string $value): Pet
    {
        return Pet::from($value);
    }
}
```

**Comment by sebastianbergmann** [comment]
Support for custom types is out of scope for this library.

**Comment by MidnightDesign** [comment]
> Support for custom types is out of scope for this library.

Alright. Still, don't you think this is a nicer way of writing this?

**Comment by sebastianbergmann** [comment]
> Still, don't you think this is a nicer way of writing this?

Yes, I do. But I had something even nicer in mind that I just had not gotten to yet.

Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.

**Pull request closed without merging**
